import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount } from "wagmi";

export default function Home() {
  const { address, isConnected } = useAccount();
  const router = useRouter();

  useEffect(() => {
    if (address) {
      localStorage.setItem("address", address);
      router.push(`/stream/${address}`);
    }
  }, [isConnected]);

  return (
    <>
      <Head>
        <title>Moments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/@widgetbot/html-embed"></script>
      </Head>
      <main className="flex space-y-5 flex-col items-center justify-center h-screen bg-black">
        {/* <h1 className="text-5xl font-extrabold text-white">Moments</h1> */}
        <img src="/moments-logo.svg" width="300" height="100" />
        <h5 className="text-lg text-white">
          Connect your Wallet to start streaming
        </h5>
        <div className="relative group">
          <div className="absolute -inset-0.5 bg-gradient-to-r from-fuchsia-600 to-blue-10 rounded-lg blur opacity-75 group-hover:opacity-100 transition duration-1000 group-hover:duration-200 animate-tilt"></div>
          <ConnectButton />
        </div>
      </main>
    </>
  );
}
